# Generated by Django 4.2.8 on 2024-04-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='summary',
            field=models.CharField(default=models.TextField(verbose_name='Текст'), max_length=155),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to=None, verbose_name='Изображения', width_field=300),
        ),
    ]
