# Generated by Django 4.2.8 on 2024-05-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='userprofile/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
